name: MASTER - Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: master
      - name: Install Dependencies
        run: npm install
      - name: Install VueJS
        run: npm install @vue/cli-service
      - name: Build
        env:
          VUE_APP_SEGMENT_KEY: ${{ secrets.SEGMENT_KEY }}
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VUE_APP_FIREBASE_DATABASE: ${{ secrets.FIREBASE_DATABASE }}
          VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VUE_APP_FIREBASE_STORAGE: ${{ secrets.FIREBASE_STORAGE }}
          VUE_APP_FIREBASE_MSG_SENDER: ${{ secrets.FIREBASE_MSG_SENDER }}
          VUE_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VUE_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: npm run build
      - name: Archive Master Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Install Dependencies Project
        run: npm install
      - name: Install Dependencies Firebase
        run: cd ./functions && npm install && cd ..
      - name: Change to master firebase project
        uses: w9jds/firebase-action@master
        with:
          args: use default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
